### ISSUE TITLE
presser doesnt fill right

### ISSUE THREAD

**Issue by CharCharthemonkey** [MatrexsVigil/harvestcraft#115]
when trying to use either applied energestics 2 or refined storage to automate the presser it fills all 3 slots and doesnt work so pretty plz fix?

**Comment by Draskh** [comment]
You can already fix this yourself, 
Put a hopper on top of the presser and connect with the ME interface. Name the ME interface "presser" or anything you need to identify in the console. After the items are pushed into the hopper they should be inserted correctly in the presser. 
This should work for Applied Energestics 2.

**Comment by CharCharthemonkey** [comment]
i will try that tho the hopper idea didnt work cause i tried it and it filled all 3 slots in the presser also the item i wanted to originally use for it didnt even have a recipe for it after checking

**Comment by Draskh** [comment]
What do you want to press?

**Comment by CharCharthemonkey** [comment]
was trying to press soybeans into tofu as a test to help a friend with her setup but it kept filling and removing from the wrong slots and not able to actually work right

**Comment by MatrexsVigil** [comment]
The automation I have set up in the code works with hoppers.  I cannot guarantee it working with other automation methods, because I can't control how they do their automation.  The apiary, presser, and both traps will accept items from the top and sides and will only output on the bottom.  Just user hoppers as a buffer between various mods.
