### ISSUE TITLE
maple chase

### ISSUE THREAD

**Issue by wesleybruce** [MatrexsVigil/harvestcraft#126]
Maple syrup and the log come out a 100 mph and can end up 12 to 20 blocks away. Chasing them everywhere. Is that intentional? Is it a glitch?  

[Technically maple syrup is tapped with a tree tap like Industrial craft rubber or a permanently attached device like a torch or item frame. Stick +bowl recipe and with an inventory of 6 or so. Maybe.  ]
Or just lower the velocity a little.

**Comment by Syndaryl** [comment]
Same issue with Paperbark trees and cinnamon. It's ... exciting but not really great.
A possible side issue: every time harvest a wood-based crop (maple syrup, paperbark, cinnamon) I get the crop and an extra log. Since they can be used as fuel and to make jungle wood (as well as for construction) I don't mind getting a log each time, but I'm not sure the intent was 100% drop rate?

**Comment by MatrexsVigil** [comment]
Fixing this.  =)
