### ISSUE TITLE
New food items not rendering in 1.10.2

### ISSUE THREAD

**Issue by Hastling** [MatrexsVigil/harvestcraft#143]
I'm using OptiFine, but not sure if it's the cause as the other items are rendering properly.

http://imgur.com/a/JHTjS

Edit: Confirmed to still happen without Optifine

**Comment by MatrexsVigil** [comment]
Thank you, I'll look into it.

**Comment by ewcaetano** [comment]
I am having the same problem using MC 1.9.4 vanilla. The new recipes appear as pink and black squares.

**Comment by icestorm972** [comment]
@MatrexsVigil  
Char Siu: misnamed model & texture file "charsuiItem.json" & "charsuiItem.json" (instead of  "charsiuItem.json" & "charsiuItem.json"), also wrong texture name in model file ("layer0": "harvestcraft:items/charsui")

The following model json files have wrong texture name for layer0 (missing "Item" in texture file name):
- biscuitsandgravyItem.json
- sweetandsoursauceItem.json
- chickenchowmeinItem.json
- sweetteaItem.json
- sesameoilItem.json
- applefritterItem.json
- fivespiceItem.json
- hotandsoursoupItem.json
- patreonpieItem.json
- creepercookieItem.json
- sweetandsourchickenItem.json
- baconandeggsItem.json
- kungpaochickenItem.json
- hoisinsauceItem.json
- noodlesItem.json

**Comment by MatrexsVigil** [comment]
Fixed!
