### ISSUE TITLE
[Bug] Trap can't be use with hopper

### ISSUE THREAD

**Issue by drakray** [MatrexsVigil/harvestcraft#159]
Hopper remove from input slot, so trap can't be automated

**Comment by neogeo0823** [comment]
I'm gonna kind of hijack this for my own issue as say that the trap can't be automated at all. I found I was able to pull items out of the output slots via Steve's Factory Manager, but that I was unable to insert bait into the traps in any way I could think of. I tried EnderIO conduits, Steve's Factory Manager, Mekanism's pipes, Thermal Foundations' ducts, Thaumcraft golems, and Botania's corporea network and redstring devices! 

Through all of it, I never managed to feed items into the input slot. The closest I achieved was funneling bait into the output slots via red string container. The golem was the saddest defeat though, as it picked up the bait, sauntered over to the trap, and just sat there, confused, and slightly worried, not knowing what to do. 

At this point, I'm almost entirely certain that these traps were purpose coded so that they can not be automated, which is just horrible. At least give us a config option or something. I've been wanting to create a large, fully automated restaurant to automatically farm and craft all of the harvestcraft recipes we've got on demand, but I'm stuck in my tracks at the point of getting raw ingredients because I'd have to come by and refill 4 dozen traps every hour. The rest of the mod's completely lovely, but this feels like something that shouldn't even be an issue.

**Comment by Syndaryl** [comment]
Not being able to input with a hopper is why you can't insert with any other block, as far as I know - the conduits and things use/abuse the hopper mechanic to insert stuff. So it's not a hijack, so much as a "mee tooo".

"Purpose Coded" is highly unlikely - you don't have to go out of your way to prevent objects to be inserted, you have to go out of your way to ALLOW it.

**Comment by neogeo0823** [comment]
If that's the case, then why not just do the extra coding needed? It seems extremely silly to leave that functionality out of the block. Especially so when inserting items via means other than direction interaction is such a ubiquitous thing, and doubly so when not only can the contents of the block be emptied without player interaction, but the red string container of Botania can insert into the output slots, but not the input slot. It gives me the impression that the mod author specifically didn't want anything to input into the trap blocks. 

The alternative is to make all my meat based food out of tofu, which is against the spirit of the soulless corporate farm-to-table chain restaurant I'm trying to create.

**Comment by drakray** [comment]
I do not think it's voluntary, because Apiary and Presser use to work with hopper, but don't work anymore
I think it's just an overlook from an update, maybe because Forge/Minecraft changed something about ISided or a thing like that
An alternative would be to use something with filter to prevent pulling of input, until it's fixed

**Comment by Syndaryl** [comment]
@neogeo0823 The mod is still being updated to 1.10.2 from a major rewrite. The traps were only barely re-added.

**Comment by neogeo0823** [comment]
We're using the 1.7.10 version of the mod though. If things will update backwards, then that's great. I'll be happy to wait for an update.

**Comment by LieseDenise** [comment]
I do not believe Pam is supporting the older versions, unfortunately.

**Comment by Jamdog** [comment]
**ModPack:** HermitPack 1.4.0
**Mod Version:** Pam's HarvestCraft 1.9.4-1.10.2h

I have discovered this bug today.  I've always used an automated Presser to make tofu in 1.7 versions of this mod, but I can no longer do this in 1.10.2.

As a workaround, it is possible to control output using Grated Hoppers or some other filtered item conduit system.

The Presser block doesn't output a comparator signal based on how full it is _(like most vanilla blocks with an inventory)_, or you would be able to have a redstone system that cuts off the input hopper - maybe adding that would also be useful for people...?

Blocks affected by this bug:

- **Presser:** Hopper above will fill both input and output slots.  Hopper below will remove from both input and output slots
- **Ground Trap:** I couldn't get a hopper to put anything into the trap.  Hopper below trap will remove from the bait slot.
- **Water Trap:** Same as Ground Trap above
- **Apiary:** Hopper cannot be used to insert a Queen Bee.  Hopper below the Apiary will remove the queen.

**Comment by Darcoon** [comment]
So I ran into this as well and thought I could work around this by using the extra utilities 2 transfer filter, this block allows you to tell it to keep only 1 item or 1 stack in.
But the sad part is that is does not seed harvestcraft blocks as a valid inventory.
To put it simple, it does not connect to them, now I don't know if this is on harvestcraf or on extra utilities 2
but I would suspect it being harvestcraft seen as it has these other problems and extra utilities works with everything else just fine.
Hope this is fixable because I do love this mod and would love to use it :)
