### ISSUE TITLE
Presser is crashing the game. (1.12c)

### ISSUE THREAD

**Issue by BSW2142** [MatrexsVigil/harvestcraft#17]
For some reason when I make the presser it will crash the game when I relaunch. Oddly tho when I create it and use it all works fine until I close game and want to come back in. Pretty much forcing me to destroy it before exiting the game. Had to play around with mcedit to pinpoint what was causing this issue. Not sure if i'm the only one having this problem. Could be the combination of mods I have installed which was my first guess but didn't seem to fix when I disabled a bunch of them trying to find which one of the mods was behind the crashing.  

Anyway keep up the good work. Really love the mod. I'll try to fix what I can on my end just wanted to point out the issue in case its happening to others.

**Comment by ghost** [comment]
I am experiencing the same issue, both with the presser and with fish traps, even in the latest release (1.12.1b).

This issue is noted in detail in #12 

They work fine until the chunk is reloaded later (usually by logging out and back in), then it causes the game to crash when loading again.

This forces me to have to go into MCEdit to delete these blocks manually any time it happens.

**Comment by MatrexsVigil** [comment]
If you are still experiencing this crash after updating to HarvestCraft 1.12.2L and Forge 2555+, please re-post here: https://github.com/MatrexsVigil/harvestcraft/issues/127
