### ISSUE TITLE
Forestry/Pam's World Crashes

### ISSUE THREAD

**Issue by MainFreak** [MatrexsVigil/harvestcraft#178]
Hello.

My game crashes every time I try to generate a new world with Pam's HarvestCraft and Forestry appearing in the crashlog. Since I am not sure which of both causes the issue ( or both? ) I reported this already on Forestry's Github. I hope this helps?
[crash-2016-10-20_22.55.34-server.txt](https://github.com/MatrexsVigil/harvestcraft/files/542896/crash-2016-10-20_22.55.34-server.txt)

**Comment by bennyman123abc** [comment]
I have a few things to point out in this crash report.

1. The crash is not being caused by HarvestCraft. However, I do not know what mod is causing the crash. I will have to look into it a little more.

2. Try generating a new world and if the problem persists, try adding mods to your environment one by one to determine what mod is causing the issue. I think the problem is being caused by CookingPlus. Don't quote me on it though!

Please reply with the results to the test I told you to perform and we will try to go from there.

Thanks!
- Ben

**Comment by MainFreak** [comment]
Hello Ben! I tested it and apparently none of the mods but Forge was causing the issue. I downgraded to an older version and it worked again. I have read that Forge changed their Config system and Immersive Engineering seemed to be involved too. Deleting the configs worked

**Comment by bennyman123abc** [comment]
Glad I could help! Have a great day and Happy Halloween!
