### ISSUE TITLE
Caused by: java.lang.NoSuchFieldError: saladfruit

### ISSUE THREAD

**Issue by xxlio109** [MatrexsVigil/harvestcraft#203]
https://gist.github.com/xxlio109/4762cb02e863dd54c02a49d7d602c660

**Comment by ghost** [comment]
Looking for you. But it take a moment.

**Comment by ghost** [comment]
Hi. 
There are many mistakes that need to be corrected first. 

I recommend a reinstall.

1. The wrong forge version
    [double click on spongeforge.jar]
    - client and server -

2. Sponge must also own the client.
    [should no plugins be installed, sponge would rather be removed from the server]
    - client and server -

5. CodeChickenCore has to be installed manually since version 1.8.
    - client and server -

3. Voxel map has the version 1.7.0 - older versions do not exist.
    [AnticAtlas is available as an alternative]
    - client -

4. JEI also needs NEI
    [Both must be installed]
    - client -


6. Waila-Hwyla is a copy.
    [Install Waila Harvestability and TheOneProbe Waile from ProfMobius]
    - client -

7. InventorryTweaks, BetterFPS, Optifine and BetterFoliage
    are also client-side mods.

8. Why NetherPortalFix? Would not it be easier to set warps or goals?

Fix these problems first and install the mods on the client first.

I'm online again.
