### ISSUE TITLE
Presser still crashing game

### ISSUE THREAD

**Issue by sherrybsweetie** [MatrexsVigil/harvestcraft#234]
Every time I try to press wax or someone on my server tries to press, the server immediately crashes. I did notice that the crash happens each time the presser ticks, and that the wax comb does not reduce in number but a bit of pressed wax is still being created. When I destroy the presser to stop the crash I am left with the original number of wax comb as well as a pressed wax for each time the server crashed before I destroy the presser. 
I'm no Java scriptor, but what I know of coding it looks like the wax comb is not being removed as the pressed wax is being created and causing a crash. 
I hope that helps you find the problem.

**Comment by lopeets** [comment]
In my experience the press only crashes when attempting to process the following 4 items:  waxcomb, fresh water, oak wood, sugar cane

I believe those are the only 4 items that yield one return item rather than 2 so its likely the crash has something to do with the empty value.  I would suggest asking people to avoid putting those items in temporarily until the mod has been updated.  That's what we're doing over here anyway :)

**Comment by chris5022** [comment]
i am having the same problem. if you can get to it and remove the wax in time it will stop crashing. hope a fix comes soon

**Comment by lopeets** [comment]
The exact problem is that the items I mentioned previously use the term "null" to reference the empty return slot.  Null is no longer used in 1.11 and the language needs to be updated by the mod dev.
