### ISSUE TITLE
Edible cotton!?

### ISSUE THREAD

**Issue by ackevac** [MatrexsVigil/harvestcraft#326]
Forge Version:1.12.2-14.23.5.2768
Mod Version:1.12.2zb
Hungry Overhaul Version:1.12.2-1.3.3.jenkins148

Cotton and jute is edible! Unbelivable! :3

One more:
When I harvest some trees they give me green fruit in block form.

**Comment by SomeRandomPetey** [comment]
Cotton is supposed to be edible, and idk what's happening with the other issue

**Comment by MatrexsVigil** [comment]
This is due to the fact that all the crops rely on the same code and honestly, Minecraft is a game not a representation of real life.  

"Steve has 36 slots in his inventory, each able to hold up to 64 blocks, meaning that he can hold 2304 blocks in total! If we take into account that every block weighs 42509.53 pounds, Steve can lift up to 97941957.12 pounds (44425720 kg)! Lets put that into perspective: The statue of liberty only weighs 450,000 pounds!"

Edible fiber crops seem...pale in caparison.  xD
