### ISSUE TITLE
1.8.9 - Version E not working properly (missing textures/recipes/items)

### ISSUE THREAD

**Issue by QueenSis** [MatrexsVigil/harvestcraft#41]
Version E of 1.8.9 does not work properly - only about four pages of items can be seen and they are mostly crops, fruits, and trees. In creative mode, I can see that there are other items and recipes, but they all show up as a missing texture both in the GUI and in the actual Minecraft world.

Version D works fine and shows all of the textures, recipes, and items, but I know some fixes were added to E that are not in D.

**Comment by Nopotato** [comment]
I'm having this problem, I recall reading someone had a fix with a script that changed the capitalization of some files, but I can't find the post again or what website it was on. Does anyone know of the fix?

**Comment by MatrexsVigil** [comment]
Not accepting non 1.12.2 bug reports at this time.

**Comment by BigClarky** [comment]
It's still an issue though, for people who play on 1.8.9

**Comment by HungryJoe** [comment]
This fix is surprisingly easy! The issue is that many of the JSON files in `assets/harvestcraft/models/item` are named `*item.json` instead of `*Item.json` (ie `kiwiitem.json` instead of `kiwiItem.json`), and so aren't being seen by the renderer. To fix the issue, just extract everything from jar into a new directory (this can be done with `jar xvf "../Pam's+HarvestCraft+1.8.9e.jar"` in Linux if you're in an empty directory you want to extract into), rename all the files (can be done by like `for fname in $(find .); do new_fname=${fname/item/Item}; mv $fname $new_fname; done;` from `assets/harvestcraft/models/item`), and jar it all back up again (via `jar cvf "../Pam's+HarvestCraft+1.8.9e.jar" *` from the root directory where the jar's contents were extracted to).
