### ISSUE TITLE
Can't craft apple sapling

### ISSUE THREAD

**Issue by DatrixTHLK** [MatrexsVigil/harvestcraft#69]
Hi Matrexs,

This first picture is your recipe for an apple sapling:
![2017-11-09 1](https://user-images.githubusercontent.com/13172036/32604274-13aa8bd8-c51b-11e7-957d-3f7ccc564be5.png)
This is what I get for doing the same recipe in a crafting table:
![2017-11-09 2](https://user-images.githubusercontent.com/13172036/32604279-163154ae-c51b-11e7-9e52-5b9d4da40c19.png)

I'm unsure of what I did wrong. It's quite possible that other saplings have this issue as well. Thanks for at least taking a look at this.

Minceraft 1.12.2
Forge: 14.23.0.2532
Pams Harvestcraft: 1.12.2a

**Comment by tabbykitty1** [comment]
Have you tried removing other mods? Is a slow process, but there may be a conflict between Pam's HarvestCraft and another mod.

I use the same version of Minecraft and HarvestCraft versions and has always worked for me.
However, I am using Forge 14.23.0.2491
![apple-acacia](https://user-images.githubusercontent.com/33450909/33208132-02dc15e4-d0d6-11e7-8063-2b12c830470e.png)
![apple-oak](https://user-images.githubusercontent.com/33450909/33208133-02ea7328-d0d6-11e7-820f-6744da5620ab.png)

**Comment by DatrixTHLK** [comment]
When I look at how you did the recipe, that might explain why I didn't see it work in my game. I'll try it out again and see if it does it this time. I've installed a mod called NoMoreRecipeConflicts. That should help do the trick.

**Comment by tabbykitty1** [comment]
The only thing that mod doesn't help with, that I've seen, has been Furnace recipes. Best of luck!
No More Recipe Conflicts has solved a minor problem with a recipe with HarvestCraft, there's 2 with the exact same material needed. With it, I get both items as a choice, vs just 1. You will also find that various recipes in HarvestCraft show up twice in the crafting table.
There's another mod you can use for the Furnace (I use InGame Config Manager because of Fried Eggs from another food mod), I do wish it worked for changing recipes in the crafting table but that was disabled in 1.12 because of errors from the added craft book.

**Comment by MatrexsVigil** [comment]
Fixed in 1.12.2
