### ISSUE TITLE
[Question 1.10.2] Mustard Seeds and Sesame Seeds

### ISSUE THREAD

**Issue by TokkenGmr** [MatrexsVigil/harvestcraft#8]
I was updating some Agricraft JSON's when someone posted [this](https://github.com/AgriCraft/AgriCraft/issues/1052#issuecomment-318857905)So I was wondering if you intended for the output of the Mustard Seed and the Sesame Seed to be replanted. As it is right no you have the seed for each that can be planted and the output for each which are seeds and they can eaten or planted. Just wanted to know if it is intended, that way I know the best way to move forward. 
Thanks in advance

**Comment by MatrexsVigil** [comment]
All crop items in HarvestCraft are meant to be used for planting (like vanilla carrots or potatoes).

**Comment by winnetrie83** [comment]
So we don't even need seeds to plant stuff? Then i don't understand why you added seeds in the first place, if they have no real purpose! For us it looks like a bug that we can plant the seed and the food item. If this isn't a bug, then there is no purpose for all those seeds. I never tried before to plant the crop item because there were seeds for a reason i though. Turns out crops can be planted.....I don't wanne be rude (not at all), but what is the purpose for the seeds?

Edit: Maybe you can add a config option to enable/disable this. I would appreciate it!

**Comment by richardhendricks** [comment]
winnetrie83 - Dial back the exclamation marks, it makes you look like a whiner.  Seriously.

The seeds were used originally, but Pam changed it recently so that there are no longer separate seeds, because honestly they're just a pain in the ass to keep around and deal with. It's just smarter overall to not use seeds because it reduces the mod size and the amount of stuff that has to be created when a new crop is made.

**Comment by winnetrie83** [comment]
@richardhendricks 

> winnetrie83 - Dial back the exclamation marks, it makes you look like a whiner. Seriously.

Wow what an attitude! Courtesy pls! I guess that's something strange to you.
That was not the intention at all. It makes you look stupid to think so!

Btw, i disagree with you. It isn't smarter. I don't see the point why it is "smarter".
For me it makes more sense to plant seeds and not the crops. Nevertheless a config option to enable disable this won't hurt after all. So people can decide for themself to use seeds to farm or just use the crops.

**Comment by richardhendricks** [comment]
*intention* is exactly what is difficult to convey with text. Excessive exclamation marks without any other emotional indicators project a feeling of exasperation and/or anger.  If that is not the feeling you want to convey, I suggest adding emoticons to let people know. Especially since your comment is asking about a feature change, the tone is automatically confrontational without additional context.

It's smarter because it:
- reduces the size of the mod. 
- reduces a player's storage requirements and inventory pressure, already really high because of mods. 
- removes the additional mindless step of creating a seed from a crop. A seed that is pretty much cookie-cutter with every other Harvestcraft seed (making unique seeds would be prohibitive anyways), and would normally exist for only a few minutes, if not seconds, in a game, before being planted or thrown away.

The only place it really would offer some gameplay is if Harvestcraft is used together with an agricultural breeding mod like Agricraft. Otherwise, seeds don't add a single gameplay option. It doesn't change or offer any sort of additional choices for the player.

**Comment by winnetrie83** [comment]
> The only place it really would offer some gameplay is if Harvestcraft is used together with an agricultural breeding mod like Agricraft. Otherwise, seeds don't add a single gameplay option. It doesn't change or offer any sort of additional choices for the player.

You're right about that, therefore i request a config option to enable/disable this. I use this mod with agricraft, but you can still plant the crops with vanilla farming disabled. Not sure who has to make it compatible (harvestcraft or agricraft), but a config option would be really helpfull.

Btw, i'm 34 years old i never intend to shout/scream/yell/cry or whatever. Why would i?
I'm not good with emoticons either. I'll try from now on, just to be sure people do not understand me wrong :-p

**Comment by MatrexsVigil** [comment]
Not accepting non 1.12.2 bug reports at this time.
