### ISSUE TITLE
[1.8.9d]crash trying to see recipes of some crops

### ISSUE THREAD

**Issue by Tsukiumy** [MatrexsVigil/harvestcraft#82]
when trying to see the recipes that uses bellpeper, the game crashes.
crashlog, http://pastebin.com/K3esSJc6

**Comment by Geethebluesky** [comment]
Your crash log shows it's Just Enough Items that is crashing. Can you try looking at the recipes with Not Enough Items and see if it crashes also?

**Comment by Syndaryl** [comment]
On 2016-04-21 8:21 PM, Gee wrote:
>
> Your crash log shows it's Just Enough Items that is crashing. Can you 
> try looking at the recipes with Not Enough Items and see if it crashes 
> also?
>

NEI isn't released for 1.8.9 - only 1.8.0

-- 
Emily Smirle - Gal Dynamo
<emily.smirle@gmail.com>

**Comment by Geethebluesky** [comment]
Yep, spoke too fast there. However since the crash is in JEI I'd start by posting for help on their forums first; the little I see about Just Enough Items, its mod support isn't very good.

**Comment by Veirilli** [comment]
This issue is addressed with the latest JEI. The issue stems from bad recipes in HarvestCraft and the update merely handles the issues in a better way by logging them rather than crashing the client.

The issues still exist in this mod however, there are many recipes that are invalid. Most have empty lists as inputs, and some have too many inputs such as the one fixed in pull request #80.
