### ISSUE TITLE
[1.9a] Item sprites looks wrong

### ISSUE THREAD

**Issue by Vorquel** [MatrexsVigil/harvestcraft#89]
The item sprites are all 90 degrees off and twice as big as they should be. Compare pixel size of Pam's foods to vanilla foods, as well as the eating animations. (Forge build 1891)

**Comment by RedBullSlurpie** [comment]
Pam this is caused because Mojang changed the way the JSON files are from 1.8 to 1.9. Just copy a vanilla JSON file for food and input your custom food into it and that will fix the food eating sideways issue and how big they are when dropped on the ground. :) just need to change all of your JSON files to the new 1.9 ones.

**Comment by Syndaryl** [comment]
Let me have a look at the change – I might be able to automate the transformation and save a lot of annoying work by hand.

**Comment by Syndaryl** [comment]
I can't even find where Mojang is hiding the vanilla JSONs :(

**Comment by Vorquel** [comment]
@Syndaryl In the 1.9 jar: assets/minecraft/models
