### ISSUE TITLE
Hopper pulls bees from apiaries

### ISSUE THREAD

**Issue by MarikCZ** [MatrexsVigil/harvestcraft#90]
Pls fix that. Maybe same thing is for traps (not tested).

**Comment by ghost** [comment]
Do you meant to Just take the things that are made in the Apiaries and not the Queen Bee itself? And adding to this, I want to make an automated Apiary so I don't have to put the Queen Bee there every single time. But Hoppers instead of putting them in the queen bee slot they go automatically into where it where the wax and honey spawn.

**Comment by MarikCZ** [comment]
Yeah, I meant that hopper pulls queen away with combs, so please fix it. Automated apiary sounds good, so far I used buildcraft pipes to automate apiaries with queen on blacklist.

**Comment by MatrexsVigil** [comment]
Fixed in 1.12.2h

**Comment by MarikCZ** [comment]
Big thanks!
Continue by this good work!
